### ISSUE TITLE
(Feature request) A toggle for prime sanctums/conditional prime sanctum inclusion

### ISSUE THREAD

**Issue by HunnyBon** [Hydraxous/BossRush#1]
I think that the mod should check whether you've completed all of the available prime sanctums (that are available as of writing), and if not all of them are completed, skip over them and complete the lap. Alternatively, it should only put you through the sanctums that you've completed.

**Comment by Hydraxous** [comment]
No plans to add this feature as I'm more or less always going to assume the majority people who are installing content addition mods to their game have already completed the game's content. Additionally, the level route can now be configured in the mod's files so anyone who wants to or doesn't want to play certain levels can change the route.
