### ISSUE TITLE
Reccomendation

### ISSUE THREAD

**Issue by DreamInSepsis** [Hydraxous/BossRush#3]
This is not for a bug, this is a reccomendation.

could you please add 7-4 into the levels? that would be greatly appreciated and make the mod even more fun with more drawn out, fun, and interesting laps.

that's it. if you're reading this and are planning on doing it, thanks in advance

**Comment by Hydraxous** [comment]
Added in Commit [f9012b0](https://github.com/Hydraxous/BossRush/commit/f9012b04632d9bf525d09737573a00b9dffc7fd0)
