### ISSUE TITLE
Bug: No button for the Boss Rush game mode

### ISSUE THREAD

**Issue by TheosCreation** [Hydraxous/BossRush#5]
![image](https://github.com/Hydraxous/BossRush/assets/83748550/cffe5c41-1886-4876-a083-2d6940c18e85)

I am on the latest version of ULTRKILL, would love to try this mod seems like what ever i do i cannot play this mod

Console:
[Message:   BepInEx] BepInEx 5.4.21.0 - ULTRAKILL (28/05/2024 10:24:41 p.m.)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [HydraDynamics 1.1.0]
[Info   :HydraDynamics] Plugin HydraDynamics is loaded!
[Warning: Unity Log] Freecam Spawned
[Info   :   BepInEx] Loading [BossRush 1.1.2]
[Info   :  BossRush] Boss Rush loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] HydraDynamics: Found info BossRush
[Info   : Unity Log] C:/Program Files (x86)/Steam/steamapps/common/ULTRAKILL/ULTRAKILL_Data/StreamingAssets/aa
[Info   : Unity Log] (LoadSceneAsync) Loading scene Intro
[Info   : Unity Log] BOSSRUSH: You are using the latest version of BossRush (1.1.2).
[Info   : Unity Log] (LoadSceneAsync) Loading scene Main Menu
[Info   :  BossRush] DeathScreen Spawned
[Info   :  BossRush] Menu Spawned
[Info   :  BossRush] Spawning Button
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BossRush.MainMenuUIPatch.SpawnButton (CanvasController __instance) (at <41ad1feed3bd465d8a6c658323a1fcf3>:0)
BossRush.MainMenuUIPatch.Postfix (CanvasController __instance) (at <41ad1feed3bd465d8a6c658323a1fcf3>:0)
CanvasController.Awake () (at <e6df654645b1486c8224892f02ea84e5>:0)

[Info   : Unity Log] /Keyboard/0
[Info   : Unity Log] <color=#50ADD8>[Discord]</color> <color=#CCE6F0>Discord initialized!</color>
Setting breakpad minidump AppID = 1229490
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199020541048 [API loaded no]
[Info   : Unity Log] <color=#4AC1E4>[Steam]</color> <color=#CCEDFF>Steam initialized!</color>
[Info   : Unity Log] <color=#5494EE>[Presence]</color> <color=#CCE0FF>Scene loaded: Main Menu</color>
[Info   : Unity Log] Set Difficulty to: 2
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 16 Data
[Info   : Unity Log] Error in finding 17 Data
[Info   : Unity Log] Error in finding 18 Data
[Info   : Unity Log] Error in finding 19 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 20 Data
[Info   : Unity Log] Error in finding 21 Data
[Info   : Unity Log] Error in finding 22 Data
[Info   : Unity Log] Error in finding 23 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 24 Data
[Info   : Unity Log] Error in finding 25 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 2 Data
[Info   : Unity Log] Error in finding 3 Data
[Info   : Unity Log] Error in finding 4 Data
[Info   : Unity Log] Error in finding 5 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 666 Data
[Info   : Unity Log] Error in finding 666 Data
[Info   : Unity Log] Error in finding 666 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 6 Data
[Info   : Unity Log] Error in finding 7 Data
[Info   : Unity Log] Error in finding 8 Data
[Info   : Unity Log] Error in finding 9 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 10 Data
[Info   : Unity Log] Error in finding 11 Data
[Info   : Unity Log] Error in finding 12 Data
[Info   : Unity Log] Error in finding 13 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 14 Data
[Info   : Unity Log] Error in finding 15 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 26 Data
[Info   : Unity Log] Error in finding 27 Data
[Info   : Unity Log] Error in finding 28 Data
[Info   : Unity Log] Error in finding 29 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 30 Data
[Info   : Unity Log] Error in finding 31 Data
[Info   : Unity Log] Error in finding 32 Data
[Info   : Unity Log] Error in finding 33 Data
[Info   : Unity Log] Secret Mission Status: 0
[Info   : Unity Log] Error in finding 34 Data
[Info   : Unity Log] Error in finding 35 Data

**Comment by TheosCreation** [comment]
looks like its just the button hopefully

probably in this section of the GamePatch.cs

//Duplicates sandbox button and configures it to open Boss rush menu
//Kind of icky but it works.
private static void SpawnButton(CanvasController __instance)
{
    BossRush.Logr.LogInfo("Spawning Button");
    RectTransform canvasRectTransform = __instance.GetComponent<RectTransform>();
    GameObject chapterSelectObject = canvasRectTransform.Find("Chapter Select").gameObject;
    if (chapterSelectObject == null)
    {
        Debug.LogError("Chapter Select object is null");
        return;
    }

    BossRushMenu.SetLastPage(chapterSelectObject);
    RectTransform chapterSelectRectTransform = chapterSelectObject.GetComponent<RectTransform>();
    GameObject sandboxButtonObject = chapterSelectObject.transform.Find("Sandbox").gameObject;

    if (sandboxButtonObject == null)
    {
        Debug.LogError("Sandbox button is null");
        return;
    }

    GameObject bossRushButtonObject = GameObject.Instantiate(sandboxButtonObject, chapterSelectRectTransform);
    bossRushButtonObject.name = "Boss Rush Button";
    Button sandboxButton = bossRushButtonObject.GetComponent<Button>();

    ColorBlock oldColorBlock = sandboxButton.colors;
    //Have to destroy old button component because of Unity's persistent listener calls.
    //They can't be removed at runtime so the component must be replaced.
    GameObject.DestroyImmediate(sandboxButton);

    Button bossRushButton = bossRushButtonObject.AddComponent<Button>();
    bossRushButton.colors = oldColorBlock;


    RectTransform bossRushButtonRectTransform = bossRushButtonObject.GetComponent<RectTransform>();

    Vector3 buttonPosition = bossRushButtonRectTransform.position;
    buttonPosition.y -= 55;
    bossRushButtonRectTransform.position = buttonPosition;

    bossRushButtonRectTransform.GetComponentInChildren<Text>().text = "BOSS RUSH";
    bossRushButton.onClick.AddListener(BossRushMenu.Open);
}

**Comment by TheosCreation** [comment]
button has no function and likes like the text didnt change, but the position of the button works so possibly just the last section of the function unless something is null prior

**Comment by TheosCreation** [comment]
the issue is on this line

bossRushButtonRectTransform.GetComponentInChildren<Text>().text = "BOSS RUSH";

the boss rush button either no longer has a Text component or you incorrectly use the type Text

heres how i found the issue:
private static void SpawnButton(CanvasController __instance)
{
    if (__instance == null)
    {
        BossRush.Logr.LogInfo("Canvas controller is null in SpawnButton");
        return;
    }

    BossRush.Logr.LogInfo("Spawning Button");
    RectTransform canvasRectTransform = __instance.GetComponent<RectTransform>();
    if (canvasRectTransform == null)
    {
        BossRush.Logr.LogInfo("Canvas RectTransform is null in SpawnButton");
        return;
    }

    GameObject chapterSelectObject = canvasRectTransform.Find("Chapter Select")?.gameObject;
    if (chapterSelectObject == null)
    {
        BossRush.Logr.LogInfo("Chapter Select object is null");
        return;
    }

    BossRushMenu.SetLastPage(chapterSelectObject);
    RectTransform chapterSelectRectTransform = chapterSelectObject.GetComponent<RectTransform>();
    if (chapterSelectRectTransform == null)
    {
        BossRush.Logr.LogInfo("Chapter Select RectTransform is null");
        return;
    }

    GameObject sandboxButtonObject = chapterSelectObject.transform.Find("Sandbox")?.gameObject;
    if (sandboxButtonObject == null)
    {
        BossRush.Logr.LogInfo("Sandbox button is null");
        return;
    }

    GameObject bossRushButtonObject = GameObject.Instantiate(sandboxButtonObject, chapterSelectRectTransform);
    if (bossRushButtonObject == null)
    {
        BossRush.Logr.LogInfo("Failed to instantiate Boss Rush button");
        return;
    }

    bossRushButtonObject.name = "Boss Rush Button";
    Button sandboxButton = bossRushButtonObject.GetComponent<Button>();
    if (sandboxButton == null)
    {
        BossRush.Logr.LogInfo("Sandbox button component is null");
        return;
    }

    ColorBlock oldColorBlock = sandboxButton.colors;
    GameObject.DestroyImmediate(sandboxButton);

    Button bossRushButton = bossRushButtonObject.AddComponent<Button>();
    if (bossRushButton == null)
    {
        BossRush.Logr.LogInfo("Failed to add Button component to Boss Rush button");
        return;
    }

    bossRushButton.colors = oldColorBlock;

    RectTransform bossRushButtonRectTransform = bossRushButtonObject.GetComponent<RectTransform>();
    if (bossRushButtonRectTransform == null)
    {
        BossRush.Logr.LogInfo("Boss Rush Button RectTransform is null");
        return;
    }

    Vector3 buttonPosition = bossRushButtonRectTransform.position;
    buttonPosition.y -= 55;
    bossRushButtonRectTransform.position = buttonPosition;


    // Get all components attached to the GameObject
    Component[] components = bossRushButtonObject.transform.GetComponentsInChildren<Component>();
    
    // Log the name of each component
    foreach (Component component in components)
    {
        BossRush.Logr.LogInfo(component.GetType());
    }

    TextMeshProUGUI buttonText = bossRushButtonObject.GetComponentInChildren<TextMeshProUGUI>();
    if (buttonText == null)
    {
        BossRush.Logr.LogInfo("Button Text component is null");
        return;
    }

    buttonText.text = "BOSS RUSH";
    bossRushButton.onClick.AddListener(BossRushMenu.Open);
}


so this is the fix for that one line of code

bossRushButtonRectTransform.GetComponentInChildren<TextMeshProUGUI>().text = "BOSS RUSH";

**Comment by TheosCreation** [comment]
im actually interested in mod development and would like to know how to properly do that, im sure its easier than having 100 debug logs even though debug logs are good practice.

**Comment by Hydraxous** [comment]
Thank you for the detailed logs and suggestions.

I wouldn't normally use so many debug logs for this kind of thing, but since UI layout and hierarchy tend to get changed often, I thought it may be a good idea for it since objects are being located by their name.

I haven't updated the mod in a very long time. So when Ultrakill updated and switched to using TextMeshPro instead of built-in Text components, of course this became a problem. Fixed [here](https://github.com/Hydraxous/BossRush/commit/f9012b04632d9bf525d09737573a00b9dffc7fd0#diff-8fd19cbe4c2755961dc561879e112fad9f52cdf39ffdf9e02985060189d275d4R244)
